using System;

namespace CubeApp.World
{
    /// <summary>
    /// Builds the surface terrain for a ground-layer chunk. A low-resolution density field (5x17x5
    /// samples covering a 16x16x128 block column) is filled with layered simplex noise, then
    /// trilinearly interpolated into blocks. A continent signal sets the base elevation and a
    /// relief signal shapes hills/mountains/valleys; a body-noise pair is blended by a vertical
    /// selector to give the strata organic variation. A surface pass replaces the top materials
    /// (grass/dirt/sand/gravel/bedrock), then caves, trees and ore features are carved in.
    /// </summary>
    public sealed class TerrainChunkProvider : IChunkProvider
    {
        private readonly int seed;

        /// <summary>Controllable monolith feature (see MonolithSculptor). A tunable tower/column
        /// feature: frequency/size/height/carve, seed-driven.</summary>
        public MonolithSculptor Monoliths { get; private set; }

        /// <summary>Sedimentary quartz veins (see QuartzVeinGenerator): layered underground veins
        /// that follow the terrain surface like real cliff strata.</summary>
        public QuartzVeinGenerator QuartzVeins { get; private set; }

        /// <summary>Coal ore blobs (see CoalOreGenerator): prefer just under the living layer
        /// (decomposed biomass), rare deep pockets anywhere.</summary>
        public CoalOreGenerator CoalOres { get; private set; }

        // Octave noise layers for each role:
        //  _bodyA/_bodyB = two terrain-body generators (16 octaves), blended by _upperSelector
        //  _upperSelector = vertical upper/lower selector (8 octaves)
        //  _surfaceA/_surfaceB = surface biomes + dirt depth (4 octaves)
        //  _continent = large-scale continent field, _relief = hills/cliffs factor
        private readonly NoiseOctaves _bodyA;
        private readonly NoiseOctaves _bodyB;
        private readonly NoiseOctaves _upperSelector;
        private readonly NoiseOctaves _surfaceA;
        private readonly NoiseOctaves _surfaceB;
        private readonly NoiseOctaves _continent;
        private readonly NoiseOctaves _relief;

        public TerrainChunkProvider(int seed = 341873128)
        {
            this.seed = seed;
            var rand = new Random(seed);
            // startIndex trims the tiny-amplitude high-frequency octaves.
            _bodyA = new NoiseOctaves(rand, 8, 8);
            _bodyB = new NoiseOctaves(rand, 8, 8);
            _upperSelector = new NoiseOctaves(rand, 8, 0);
            _surfaceA = new NoiseOctaves(rand, 4, 0);
            _surfaceB = new NoiseOctaves(rand, 4, 0);
            _continent = new NoiseOctaves(rand, 8, 2);
            _relief = new NoiseOctaves(rand, 8, 8);
            Monoliths = new MonolithSculptor(seed);
            QuartzVeins = new QuartzVeinGenerator(seed);
            CoalOres = new CoalOreGenerator(seed);
        }

        public Chunk GenerateChunk(int chunkX, int chunkZ, int chunkSize, int chunkHeight)
        {
            int originX = chunkX * chunkSize;
            int originZ = chunkZ * chunkSize;
            // Ground layer: OriginY=-64, local Y 0..447 = world -64..383.
            const int originY = ChunkManager.GroundOriginY;
            var chunk = new Chunk(chunkSize, chunkHeight, chunkSize, originX, originY, originZ);

            // The terrain band occupies local Y 0..127 (world -64..63) at the TOP of the ground
            // layer. Sea level is local 64 (world 0). Above the band (world 64..383) is open sky.
            // The DEEP world (-256..-65) is a separate layer generated by DeepChunkProvider.
            const int terrainBandStart = 0; // local Y where the terrain band begins (world -64)
            const int seaLevelLocalY = terrainBandStart + 64;

            int idBedrock = BlockRegistry.GetId("bedrock");
            int idWater = BlockRegistry.GetId("water");
            int idStone = BlockRegistry.GetId("stone");
            int idGrass = BlockRegistry.GetId("grass");
            int idDirt = BlockRegistry.GetId("dirt");
            int idSand = BlockRegistry.GetId("sand");
            int idGravel = BlockRegistry.GetId("gravel");

            // ---- Build the 5 x 17 x 5 density field ----
            // Field x/z are in 4-block units (5 samples cover the chunk's 16 blocks), field y
            // in 8-block units (17 samples cover 128).
            const int fxCount = 5, fyCount = 17, fzCount = 5;
            const double baseFreq = 684.412;
            double[] field = new double[fxCount * fyCount * fzCount];

            for (int fx = 0; fx < fxCount; fx++)
            {
                double xq = (chunkX * 4 + fx); // x field coord = worldX/4
                for (int fz = 0; fz < fzCount; fz++)
                {
                    double zq = (chunkZ * 4 + fz); // z field coord = worldZ/4
                    int col = (fx * fzCount + fz) * fyCount;

                    // Large-scale elevation: continent field + a sharpened relief signal.
                    double continent = _continent.Noise2D(xq, zq);
                    double relief = _relief.Noise2D(xq * 100.0, zq * 100.0);

                    double elevation = (continent + 256.0) / 512.0;
                    if (elevation > 1.0) elevation = 1.0;

                    double reliefShaped = relief / 8000.0;
                    if (reliefShaped < 0.0) reliefShaped = -reliefShaped;
                    reliefShaped = reliefShaped * 3.0 - 3.0;
                    if (reliefShaped < 0.0)
                    {
                        reliefShaped /= 2.0;
                        if (reliefShaped < -1.0) reliefShaped = -1.0;
                        reliefShaped /= 1.4;
                        reliefShaped /= 2.0;
                        elevation = 0.0;
                    }
                    else
                    {
                        if (reliefShaped > 1.0) reliefShaped = 1.0;
                        reliefShaped /= 6.0;
                    }
                    elevation += 0.5;
                    reliefShaped = reliefShaped * fyCount / 16.0;
                    double centerHeight = fyCount / 2.0 + reliefShaped * 4.0; // surface line in field-y units

                    for (int fy = 0; fy < fyCount; fy++)
                    {
                        int idx = col + fy;
                        double yq = fy; // y field coord = worldY/8

                        // Terrain body + vertical selector blend.
                        double bodyA = _bodyA.Noise3D(xq * baseFreq, yq * baseFreq, zq * baseFreq) / 512.0;
                        double bodyB = _bodyB.Noise3D(xq * baseFreq, yq * baseFreq, zq * baseFreq) / 512.0;
                        double selector = (_upperSelector.Noise3D(xq * (baseFreq / 80.0), yq * (baseFreq / 160.0), zq * (baseFreq / 80.0)) / 10.0 + 1.0) / 2.0;

                        double density;
                        if (selector < 0.0) density = bodyA;
                        else if (selector > 1.0) density = bodyB;
                        else density = bodyA + (bodyB - bodyA) * selector;

                        // Falloff: push density solid below the surface line, air above.
                        double falloff = ((double)fy - centerHeight) * 12.0 / elevation;
                        if (falloff < 0.0) falloff *= 4.0;
                        density -= falloff;

                        // Force air in the top field rows.
                        if (fy > fyCount - 4)
                        {
                            double clamp = (double)(fy - (fyCount - 4)) / 3.0;
                            density = density * (1.0 - clamp) + -10.0 * clamp;
                        }

                        field[idx] = density;
                    }
                }
            }

            // ---- generateTerrain: trilinear-interpolate the field into blocks ----
            // The terrain band occupies local Y terrainBandStart..terrainBandStart+127; above it is
            // open sky. Water below the band's sea level.
            for (int ly = 0; ly < 128; ly++)
            {
                int localY = terrainBandStart + ly;
                double gy = ly / 8.0;
                int fy0 = (int)gy;
                int fy1 = fy0 + 1;
                double ty = gy - fy0;
                if (fy0 > 15) { fy0 = 15; fy1 = 16; ty = 1.0; }

                for (int lx = 0; lx < chunkSize; lx++)
                {
                    double gx = lx / 4.0;
                    int fx0 = (int)gx;
                    int fx1 = fx0 + 1;
                    double tx = gx - fx0;
                    if (fx0 > 3) { fx0 = 3; fx1 = 4; tx = 1.0; }

                    for (int lz = 0; lz < chunkSize; lz++)
                    {
                        double gz = lz / 4.0;
                        int fz0 = (int)gz;
                        int fz1 = fz0 + 1;
                        double tz = gz - fz0;
                        if (fz0 > 3) { fz0 = 3; fz1 = 4; tz = 1.0; }

                        double density = Trilinear(field, fx0, fy0, fz0, fx1, fy1, fz1, fxCount, fyCount, fzCount, tx, ty, tz);

                        int block;
                        if (density > 0.0) block = idStone;
                        else if (localY < seaLevelLocalY) block = idWater;
                        else block = 0;
                        chunk[lx, localY, lz] = block;
                    }
                }
            }

            // ---- Surface materials pass ----
            ReplaceBlocks(chunkX, chunkZ, chunk, idBedrock, idWater, idStone, idGrass, idDirt, idSand, idGravel, terrainBandStart);

            // ---- caves and trees ----
            GenerateCaves(chunkX, chunkZ, chunk, terrainBandStart);
            GenerateTrees(chunkX, chunkZ, chunk);

            // ---- monoliths (controllable feature; runs after caves so towers stand on ground) ----
            Monoliths.Sculpt(chunk, terrainBandStart, chunkSize, chunkHeight);

            // ---- sedimentary quartz veins (follows terrain, like cliff strata) ----
            QuartzVeins.Generate(chunk, chunkX, chunkZ, terrainBandStart, chunkSize, chunkHeight);

            // ---- coal ore (biomass coal just under the living layer, rare deep pockets) ----
            CoalOres.Generate(chunk, chunkX, chunkZ, terrainBandStart, chunkSize, chunkHeight);

            chunk.NeedsRemesh = true;
            return chunk;
        }

        // Trilinear interpolation over the density field. Field layout is column-major:
        // ((fx * fzCount) + fz) * fyCount + fy (matches Java's ((x*zSize + z)*ySize + y)).
        private static double Trilinear(double[] f, int fx0, int fy0, int fz0, int fx1, int fy1, int fz1,
            int fxCount, int fyCount, int fzCount, double tx, double ty, double tz)
        {
            int zStride = fyCount;
            int xStride = fzCount * fyCount;
            double c000 = f[fx0 * xStride + fz0 * zStride + fy0];
            double c100 = f[fx1 * xStride + fz0 * zStride + fy0];
            double c010 = f[fx0 * xStride + fz1 * zStride + fy0];
            double c110 = f[fx1 * xStride + fz1 * zStride + fy0];
            double c001 = f[fx0 * xStride + fz0 * zStride + fy1];
            double c101 = f[fx1 * xStride + fz0 * zStride + fy1];
            double c011 = f[fx0 * xStride + fz1 * zStride + fy1];
            double c111 = f[fx1 * xStride + fz1 * zStride + fy1];

            double x00 = Lerp(c000, c100, tx);
            double x10 = Lerp(c010, c110, tx);
            double x01 = Lerp(c001, c101, tx);
            double x11 = Lerp(c011, c111, tx);

            double z0 = Lerp(x00, x10, tz);
            double z1 = Lerp(x01, x11, tz);
            return Lerp(z0, z1, ty);
        }

        // Surface materials pass: scans each column top-down, replaces the surface stone with
        // grass/dirt (or sand/gravel in their biomes), fills bedrock at the bottom.
        private void ReplaceBlocks(int chunkX, int chunkZ, Chunk chunk,
            int idBedrock, int idWater, int idStone, int idGrass, int idDirt, int idSand, int idGravel,
            int terrainBandStart)
        {
            byte[] blocks = chunk.RawBlocks;
            const int height = ChunkManager.ChunkHeight; // 448
            const int width = 16;
            const int seaLevel = 64; // relative to the terrain band start (world 0)
            var rand = new Random(unchecked(chunkX * 341873128 + chunkZ * 132897987 ^ seed));
            const double inv32 = 1.0 / 32.0;

            for (int x = 0; x < width; x++)
            {
                for (int z = 0; z < width; z++)
                {
                    double wx = chunkX * width + x;
                    double wz = chunkZ * width + z;

                    // Sand biome: surfaceA at (x/32, z/32, 0) > 0. Gravel biome: surfaceA at a
                    // rotated offset > 3. Dirt depth: surfaceB 2D octaves /3 + 3.
                    bool sandy = _surfaceA.Noise3D(wx * inv32, wz * inv32, 0.0) + rand.NextDouble() * 0.2 > 0.0;
                    bool gravelly = _surfaceA.Noise3D(wz * inv32, 109.0134, wx * inv32) + rand.NextDouble() * 0.2 > 3.0;
                    int dirtDepth = (int)(_surfaceB.Noise2D(wx * inv32 * 2.0, wz * inv32 * 2.0) / 3.0 + 3.0 + rand.NextDouble() * 0.25);

                    int depthRemaining = -1; // -1 = haven't found the surface yet
                    int topBlock = idGrass;
                    int fillBlock = idDirt;

                    // Scan the terrain band (band-relative 127..0, actual local terrainBandStart..+127).
                    for (int bandLy = 127; bandLy >= 0; bandLy--)
                    {
                        int ly = terrainBandStart + bandLy;
                        int idx = (x * width + z) * height + ly;

                        if (bandLy <= rand.Next(6) - 1)
                        {
                            blocks[idx] = (byte)idBedrock;
                        }
                        else if (blocks[idx] == 0)
                        {
                            depthRemaining = -1;
                        }
                        else if (blocks[idx] == idStone)
                        {
                            if (depthRemaining == -1)
                            {
                                if (dirtDepth <= 0)
                                {
                                    topBlock = 0;
                                    fillBlock = idStone;
                                }
                                else if (bandLy >= seaLevel - 4 && bandLy <= seaLevel + 1)
                                {
                                    topBlock = idGrass;
                                    fillBlock = idDirt;
                                    if (gravelly)
                                    {
                                        topBlock = 0;
                                        fillBlock = idGravel;
                                    }
                                    if (sandy)
                                    {
                                        topBlock = idSand;
                                        fillBlock = idSand;
                                    }
                                }
                                if (bandLy < seaLevel && topBlock == 0) topBlock = idWater;
                                depthRemaining = dirtDepth;
                                blocks[idx] = (byte)(bandLy >= seaLevel - 1 ? topBlock : fillBlock);
                            }
                            else if (depthRemaining > 0)
                            {
                                depthRemaining--;
                                blocks[idx] = (byte)fillBlock;
                            }
                        }
                    }
                }
            }
        }

        // Cave generation: a per-chunk deterministic chance of spawning random-walker tunnels that
        // carve winding, branching tubes through the stone.
        private void GenerateCaves(int chunkX, int chunkZ, Chunk chunk, int terrainBandStart)
        {
            byte[] blocks = chunk.RawBlocks;

            // Iterate a 17x17 region of neighbour-chunk seeds and spawn walkers at the NEIGHBOR
            // chunk's coordinates, carving into THIS chunk's block array. That way a cave that
            // starts in a neighbouring chunk crosses the border and continues here - without this,
            // every tunnel dies at the chunk edge because the walker can only carve the current
            // chunk's blocks.
            var rand = new Random(seed);
            long seedA = rand.Next() * 2L + 1L;
            long seedB = rand.Next() * 2L + 1L;

            for (int nx = chunkX - 8; nx <= chunkX + 8; nx++)
            {
                for (int nz = chunkZ - 8; nz <= chunkZ + 8; nz++)
                {
                    var rand2 = new Random(unchecked((int)((long)nx * seedA + (long)nz * seedB ^ seed)));

                    int caveCount = rand2.Next(rand2.Next(rand2.Next(40) + 1) + 1);
                    if (rand2.Next(15) != 0) caveCount = 0;

                    for (int c = 0; c < caveCount; c++)
                    {
                        // Walker starts in the NEIGHBOR chunk (nx/nz), so its tunnel can reach
                        // across the border into this chunk.
                        double x = nx * 16 + rand2.Next(16);
                        // Y is confined to the terrain band. Some caves spawn LOW so they can
                        // descend through the bedrock floor and open a passage down into the deep
                        // layer (the deep chunk below mirrors these openings via
                        // ChunkManager.SyncDeepAccess).
                        double y = (rand2.Next(3) == 0)
                            ? terrainBandStart + rand2.Next(16)      // deep diver: digs toward the floor
                            : terrainBandStart + rand2.Next(rand2.Next(120) + 8);
                        double z = nz * 16 + rand2.Next(16);

                        int nodeCount = 1;
                        if (rand2.Next(4) == 0)
                        {
                            GenerateCaveNode(chunk, blocks, chunkX, chunkZ, rand2,
                                x, y, z, (float)(rand2.NextDouble() * 2.0 + rand2.NextDouble()), 0f, 0f, -1, -1, 1.0);
                            nodeCount += rand2.Next(4);
                        }

                        for (int n = 0; n < nodeCount; n++)
                        {
                            float yaw = (float)(rand2.NextDouble() * Math.PI * 2.0);
                            float pitch = (float)((rand2.NextDouble() - 0.5) * 2.0 / 8.0);
                            float size = (float)(rand2.NextDouble() * 2.0 + rand2.NextDouble());

                            // Deep caves have a small chance to spawn 5x as fat - the walker's
                            // size drives the tunnel radius, so x5 turns a ~2-4 wide tube into a
                            // ~20-wide chamber. Only in the lower terrain band and ~1 in 8 nodes.
                            if (y < terrainBandStart + 60 && rand2.Next(8) == 0)
                            {
                                size *= 5f;
                            }

                            GenerateCaveNode(chunk, blocks, chunkX, chunkZ, rand2, x, y, z, size, yaw, pitch, 0, 0, 1.0);
                        }
                    }
                }
            }
        }

        // One random-walker cave tube: advances in the yaw/pitch direction, carving a round tube
        // whose radius bulges in the middle, wobbling as it goes and branching at the midpoint.
        private void GenerateCaveNode(Chunk chunk, byte[] blocks, int chunkX, int chunkZ, Random rand,
            double x, double y, double z, float size, float yaw, float pitch, int start, int maxLength, double scale)
        {
            double cx = chunkX * 16 + 8;
            double cz = chunkZ * 16 + 8;
            var rng = new Random(rand.Next());
            float wobbleYaw = 0f;
            float wobblePitch = 0f;
            byte idWater = (byte)BlockRegistry.GetId("water");
            byte idGrass = (byte)BlockRegistry.GetId("grass");
            byte idDirt = (byte)BlockRegistry.GetId("dirt");

            if (maxLength <= 0) maxLength = 112 - rng.Next(112 / 4);
            bool branch = false;
            if (start == -1)
            {
                start = maxLength / 2;
                branch = true;
            }
            int branchAt = rng.Next(maxLength / 2) + maxLength / 4;

            const int height = ChunkManager.ChunkHeight; // 256 (local Y 0..255)

            for (int len = start; len < maxLength; len++)
            {
                double radius = 1.5 + Math.Sin(len * Math.PI / maxLength) * size;
                double vRadius = radius * scale;

                x += Math.Cos(yaw) * Math.Cos(pitch);
                y += Math.Sin(pitch);
                z += Math.Sin(yaw) * Math.Cos(pitch);

                if (rng.Next(6) == 0) pitch *= 0.92f;
                else pitch *= 0.7f;
                pitch += wobblePitch * 0.1f;
                yaw += wobbleYaw * 0.1f;
                wobblePitch *= 0.9f;
                wobbleYaw *= 12f / 16f;
                wobblePitch += (float)((rng.NextDouble() - rng.NextDouble()) * rng.NextDouble() * 2.0);
                wobbleYaw += (float)((rng.NextDouble() - rng.NextDouble()) * rng.NextDouble() * 4.0);

                if (!branch && len == branchAt && size > 1.0f)
                {
                    GenerateCaveNode(chunk, blocks, chunkX, chunkZ, rng, x, y, z,
                        (float)(rng.NextDouble() * 0.5 + 0.5), yaw - (float)Math.PI * 0.5f, pitch / 3f, len, maxLength, 1.0);
                    GenerateCaveNode(chunk, blocks, chunkX, chunkZ, rng, x, y, z,
                        (float)(rng.NextDouble() * 0.5 + 0.5), yaw + (float)Math.PI * 0.5f, pitch / 3f, len, maxLength, 1.0);
                    return;
                }

                // Stop when the walker leaves the chunk's neighbourhood.
                double dx = x - cx;
                double dz = z - cz;
                double remaining = maxLength - len;
                double bound = size + 2.0 + 16.0;
                if (dx * dx + dz * dz - remaining * remaining > bound * bound) return;

                int minX = (int)Math.Floor(x - radius) - chunkX * 16 - 1;
                int maxX = (int)Math.Floor(x + radius) - chunkX * 16 + 1;
                int minY = (int)Math.Floor(y - vRadius) - 1;
                int maxY = (int)Math.Floor(y + vRadius) + 1;
                int minZ = (int)Math.Floor(z - radius) - chunkZ * 16 - 1;
                int maxZ = (int)Math.Floor(z + radius) - chunkZ * 16 + 1;
                if (minX < 0) minX = 0;
                if (maxX > 16) maxX = 16;
                if (minY < 0) minY = 0; // allow caves to punch through the bedrock floor (local 0)
                if (maxY > height - 1) maxY = height - 1;
                if (minZ < 0) minZ = 0;
                if (maxZ > 16) maxZ = 16;

                for (int lx = minX; lx < maxX; lx++)
                {
                    double ndx = (lx + chunkX * 16 + 0.5 - x) / radius;
                    for (int lz = minZ; lz < maxZ; lz++)
                    {
                        double ndz = (lz + chunkZ * 16 + 0.5 - z) / radius;
                        for (int ly = maxY; ly >= minY; ly--)
                        {
                            double ndy = (ly + 0.5 - y) / vRadius;
                            if (ndx * ndx + ndy * ndy + ndz * ndz < 1.0)
                            {
                                int idx = (lx * 16 + lz) * height + ly;
                                byte id = blocks[idx];
                                if (id == idWater) continue; // don't carve water
                                if (id == 0) continue;        // already air
                                blocks[idx] = 0;
                                // If the cave opened through a surface grass block, let the grass
                                // settle one block down so no floating grass is left over a mouth.
                                if (id == idGrass && ly > 1 && blocks[idx - 1] == idDirt)
                                {
                                    blocks[idx - 1] = idGrass;
                                }
                            }
                        }
                    }
                }
            }
        }

        // Trees: a few per chunk on grass, each a 4-6 tall trunk with a rounded leaf canopy (top
        // corners cut for the plus shape). Trees that would cross the chunk edge fail their
        // clearance check and don't spawn.
        private void GenerateTrees(int chunkX, int chunkZ, Chunk chunk)
        {
            byte[] blocks = chunk.RawBlocks;
            var rand = new Random(unchecked(chunkX * 341873128 + chunkZ * 132897987 ^ seed) ^ 0x9E3779);
            byte idWood = (byte)BlockRegistry.GetId("log");
            byte idLeaves = (byte)BlockRegistry.GetId("leaves");
            byte idGrass = (byte)BlockRegistry.GetId("grass");
            byte idDirt = (byte)BlockRegistry.GetId("dirt");
            const int height = ChunkManager.ChunkHeight;

            int treeCount = rand.Next(6);
            if (rand.Next(10) == 0) treeCount++;

            for (int t = 0; t < treeCount; t++)
            {
                int lx = rand.Next(16);
                int lz = rand.Next(16);
                int surfaceY = -1;
                for (int y = height - 1; y >= 0; y--)
                {
                    if (blocks[(lx * 16 + lz) * height + y] != 0)
                    {
                        surfaceY = y;
                        break;
                    }
                }
                if (surfaceY <= 0) continue;
                // The trunk starts one block ABOVE the surface block (which must be grass/dirt).
                GenerateTree(blocks, lx, surfaceY + 1, lz, rand, idWood, idLeaves, idGrass, idDirt);
            }
        }

        // One tree rooted with its trunk base at (x, baseY, z) - baseY is the first trunk cell,
        // the ground (grass/dirt) sits at baseY-1.
        private void GenerateTree(byte[] blocks, int x, int baseY, int z, Random rand,
            byte idWood, byte idLeaves, byte idGrass, byte idDirt)
        {
            const int height = ChunkManager.ChunkHeight;
            int trunkHeight = rand.Next(3) + 4;

            // Clearance: the trunk column and canopy footprint must be air or leaves.
            for (int y = baseY; y <= baseY + 1 + trunkHeight && y < height; y++)
            {
                int radius = 1;
                if (y == baseY) radius = 0;
                if (y >= baseY + 1 + trunkHeight - 2) radius = 2;
                for (int dx = -radius; dx <= radius; dx++)
                {
                    for (int dz = -radius; dz <= radius; dz++)
                    {
                        int lx = x + dx;
                        int lz = z + dz;
                        if (lx < 0 || lx >= 16 || lz < 0 || lz >= 16 || y < 0 || y >= height) return;
                        byte b = blocks[(lx * 16 + lz) * height + y];
                        if (b != 0 && b != idLeaves) return;
                    }
                }
            }

            // The ground must be grass or dirt.
            if (baseY < 1) return;
            byte ground = blocks[(x * 16 + z) * height + (baseY - 1)];
            if (ground != idGrass && ground != idDirt) return;

            // Shade the ground under the tree with dirt.
            blocks[(x * 16 + z) * height + (baseY - 1)] = idDirt;

            // Canopy: radius grows downward; the top row corners are always cut (plus shape),
            // lower-row corners are randomly trimmed.
            for (int y = baseY - 3 + trunkHeight; y <= baseY + trunkHeight && y < height; y++)
            {
                if (y < 0) continue;
                int dy = y - (baseY + trunkHeight);
                int radius = 1 - dy / 2;
                for (int dx = -radius; dx <= radius; dx++)
                {
                    for (int dz = -radius; dz <= radius; dz++)
                    {
                        int ax = Math.Abs(dx);
                        int az = Math.Abs(dz);
                        if (ax != radius || az != radius || (rand.Next(2) != 0 && dy != 0))
                        {
                            int lx = x + dx;
                            int lz = z + dz;
                            if (lx < 0 || lx >= 16 || lz < 0 || lz >= 16) continue;
                            int idx = (lx * 16 + lz) * height + y;
                            byte b = blocks[idx];
                            if (b == 0 || b == idLeaves) blocks[idx] = idLeaves;
                        }
                    }
                }
            }

            // Trunk: only replace air or leaves so the trunk doesn't punch through terrain.
            for (int i = 0; i < trunkHeight; i++)
            {
                int y = baseY + i;
                if (y < 0 || y >= height) break;
                int idx = (x * 16 + z) * height + y;
                byte b = blocks[idx];
                if (b == 0 || b == idLeaves) blocks[idx] = idWood;
            }
        }

        public string BiomeNameAt(int worldX, int worldZ)
        {
            // Same continent/relief sampling as the terrain; classify by expected land height.
            double xq = worldX / 4.0;
            double zq = worldZ / 4.0;
            double continent = _continent.Noise2D(xq, zq);
            double relief = _relief.Noise2D(xq * 100.0, zq * 100.0);

            double elevation = (continent + 256.0) / 512.0;
            if (elevation > 1.0) elevation = 1.0;
            double reliefShaped = relief / 8000.0;
            if (reliefShaped < 0.0) reliefShaped = -reliefShaped;
            reliefShaped = reliefShaped * 3.0 - 3.0;
            if (reliefShaped < 0.0)
            {
                reliefShaped /= 2.0;
                if (reliefShaped < -1.0) reliefShaped = -1.0;
                reliefShaped /= 1.4;
                reliefShaped /= 2.0;
                elevation = 0.0;
            }
            else
            {
                if (reliefShaped > 1.0) reliefShaped = 1.0;
                reliefShaped /= 6.0;
            }
            elevation += 0.5;
            double centerY = (17.0 / 2.0 + (reliefShaped * 17.0 / 16.0) * 4.0) * 8.0; // block Y of the surface line

            if (centerY < 56) return "Ocean";
            if (reliefShaped > 0.12) return "Mountains";
            if (reliefShaped > 0.0) return "Hills";
            return "Plains";
        }

        private static double Lerp(double a, double b, double t)
        {
            return a + (b - a) * t;
        }
    }
}
