using System;
using System.Collections.Generic;

namespace Cubuild
{
    /// <summary>
    /// An A* pathfinder over the block grid. Moves are generated by
    /// <see cref="PathNodeProcessor"/>; the search is capped at 200 node expansions and returns a
    /// <see cref="PathEntity"/> of waypoints, or null when no route is found within budget.
    ///
    /// Neighbour generation is a simple 8-direction horizontal walk + 1 step-up/step-down per move
    /// (never jumps more than one block). Vertical shafts are intentionally not followed - mobs
    /// path on the ground.
    /// </summary>
    public sealed class PathFinder
    {
        private readonly PathHeap _path = new();
        private readonly HashSet<PathPoint> _closedSet = new();
        private readonly PathNodeProcessor _processor;
        private readonly PathPoint[] _pathOptions = new PathPoint[32];
        private readonly Dictionary<(int X, int Y, int Z), PathPoint> _nodeCache = new();
        private const int MaxIterations = 2000;

        public PathFinder(PathNodeProcessor processor)
        {
            _processor = processor;
        }

        public PathEntity? FindPath(double startX, double startY, double startZ,
            double goalX, double goalY, double goalZ, float maxDistance)
        {
            _path.ClearPath();
            _closedSet.Clear();
            _nodeCache.Clear();

            PathPoint start = _processor.GetStart(startX, startY, startZ);
            PathPoint goal = _processor.GetPathPointToCoords(goalX, goalY, goalZ);

            start.TotalPathDistance = 0f;
            start.DistanceToNext = start.DistanceManhattan(goal);
            start.DistanceToTarget = start.DistanceToNext;
            _path.AddPoint(start);

            PathPoint best = start;
            int iterations = 0;

            while (!_path.IsEmpty)
            {
                iterations++;
                if (iterations >= MaxIterations) break;

                PathPoint current = _path.Dequeue();

                if (current.Equals(goal))
                {
                    best = current; // the dequeued cached node carries the full Previous chain
                    break;
                }

                if (current.DistanceManhattan(goal) < best.DistanceManhattan(goal))
                {
                    best = current;
                }

                current.Visited = true;
                _closedSet.Add(current);

                int count = FindPathOptions(current, goal, maxDistance);
                for (int i = 0; i < count; i++)
                {
                    PathPoint next = _pathOptions[i];
                    float stepCost = current.DistanceManhattan(next);
                    next.DistanceFromOrigin = current.DistanceFromOrigin + stepCost;
                    next.Cost = stepCost + next.CostMalus;
                    float f = current.TotalPathDistance + next.Cost;

                    if (next.DistanceFromOrigin <= maxDistance && (!next.Assigned || f < next.TotalPathDistance))
                    {
                        next.Previous = current;
                        next.TotalPathDistance = f;
                        next.DistanceToNext = next.DistanceManhattan(goal) + next.CostMalus;

                        if (next.Assigned)
                        {
                            _path.ChangeDistance(next, next.TotalPathDistance + next.DistanceToNext);
                        }
                        else
                        {
                            next.DistanceToTarget = next.TotalPathDistance + next.DistanceToNext;
                            _path.AddPoint(next);
                        }
                    }
                }
            }

            if (best == start) return null;

            return CreateEntityPath(start, best);
        }

        private int FindPathOptions(PathPoint point, PathPoint target, float maxDistance)
        {
            int count = 0;

            // 8 horizontal neighbours (including diagonals so mobs can cut corners).
            for (int dx = -1; dx <= 1; dx++)
            {
                for (int dz = -1; dz <= 1; dz++)
                {
                    if (dx == 0 && dz == 0) continue;

                    if (count >= _pathOptions.Length) break;

                    int nx = point.X + dx;
                    int nz = point.Z + dz;

                    // Try same level first.
                    if (TryNode(nx, point.Y, nz, target, maxDistance, out var same))
                    {
                        _pathOptions[count++] = same;
                        continue;
                    }

                    // Then one block up (step-up) and one block down (step-down).
                    if (TryNode(nx, point.Y + 1, nz, target, maxDistance, out var up))
                    {
                        _pathOptions[count++] = up;
                    }
                    else if (TryNode(nx, point.Y - 1, nz, target, maxDistance, out var down))
                    {
                        _pathOptions[count++] = down;
                    }
                }
            }

            return count;
        }

        private bool TryNode(int x, int y, int z, PathPoint target, float maxDistance, out PathPoint node)
        {
            node = null!;
            if (!_processor.IsStandable(x, y, z)) return false;

            // Skip nodes already visited/closed or beyond the search radius.
            if (DistanceManhattan(x, y, z, target) > maxDistance) return false;

            // Reuse the cached instance for this cell so Assigned/Previous state is shared and the
            // heap never ends up with duplicate PathPoint objects for one cell.
            if (!_nodeCache.TryGetValue((x, y, z), out node!))
            {
                node = new PathPoint(x, y, z);
                // Breakable blocks get a cost penalty so the pathfinder prefers going around,
                // but CAN route through them as a last resort.
                node.CostMalus = _processor.BlockCostMalus(x, y, z);
                _nodeCache[(x, y, z)] = node;
            }
            if (node.Visited) return false;

            return true;
        }

        private PathEntity CreateEntityPath(PathPoint start, PathPoint end)
        {
            var points = new List<PathPoint>();
            PathPoint? current = end;
            while (current != null && !current.Equals(start))
            {
                points.Add(current);
                current = current.Previous;
            }
            points.Reverse();
            return new PathEntity(points.ToArray());
        }

        private static int DistanceManhattan(int x, int y, int z, PathPoint target)
            => Math.Abs(target.X - x) + Math.Abs(target.Y - y) + Math.Abs(target.Z - z);
    }
}
